### ISSUE TITLE
Timeline for code?

### ISSUE THREAD

**Issue by Taytay** [chujiezheng/LLM-MCQ-Bias#1]
Hi there! I read the paper and quite enjoyed it. Nice work. I was excited to see that there was accompanying code. I'm not sure if you have to wait on something related to the timeline of the paper, but I'd love to get to experiment with the code.

**Comment by chujiezheng** [comment]
Hi, thanks for your nice words! Sorry for not updating yet, but I've been a bit busy lately. I plan to release the experimental results and codes before February 10th. Stay tuned!

By the way, you may find the codes we uploaded on OpenReview, which you can use for quick basic experiments!

**Comment by Taytay** [comment]
Oh, that's fantastic news. I had totally missed that!
(for anyone else that stumbles on this: https://openreview.net/forum?id=shr9PXz7T0 -> Supplementary Material: [ zip](https://openreview.net/attachment?id=shr9PXz7T0&name=supplementary_material)

**Comment by chujiezheng** [comment]
Hi, I have uploaded the [code](https://github.com/chujiezheng/LLM-MCQ-Bias/tree/main/code) and the [experimental results](https://github.com/chujiezheng/LLM-MCQ-Bias_data). Enjoy them!
