### ISSUE TITLE
Excluded samples from MMLU

### ISSUE THREAD

**Issue by aviaefrat** [chujiezheng/LLM-MCQ-Bias#2]
In Appendix E you wrote:
We excluded a few MMLU samples (about 3.2% in total), where the options refer to each other like “A and B”, “none of the above”, in all the experiments.
I found code referencing that at:
https://github.com/chujiezheng/LLM-MCQ-Bias/blob/main/code/utils.py#L17
Are there any more locations that I'm missing?

**Comment by chujiezheng** [comment]
https://github.com/chujiezheng/LLM-MCQ-Bias/blob/826a81b8f19db6aad6c5828fbeb60c3d4a0a8502/code/utils.py#L50C5-L50C21
