### ISSUE TITLE
How do you calculate RStd in your works?

### ISSUE THREAD

**Issue by kenchung285** [chujiezheng/LLM-MCQ-Bias#5]
Hi! 
I have read your paper works, it's great. I want to confirm my thoughts of calculating the RStd, so I go to check your source code. Is the boostrap_std means the RStd?

Followings are my thought of how to calculate RStd.
If choices are A/B/C/D
1. calculate the accuracy of those questions that the correct answers are A/B/C/D respectively. 
   So you got four accuracy corresponding to different correct answers.
2. Then calculate the standard deviation of the four accuracy you got in the first step
    RStd is this standard deviation

Besides, do you have any references about RStd?

Thank you for answering my questions.

**Comment by chujiezheng** [comment]
RStd is the standard deviation of the recalls, as calculated below

https://github.com/chujiezheng/LLM-MCQ-Bias/blob/e78748b673346f3b307e728e68eb48a0f1baf2bc/code/debias_pride.py#L153

**Comment by imhgchoi** [comment]
Hello authors, thanks for the impressive work!!

Following up on this question, correct me if my understanding is wrong.
if the predictions for a 3-option are ['A', 'A', 'C'] where the gt are ['A', 'B', 'C'], are we computing something like,

A_recall = recall(prediction=[1, 1, 0], labels=[1, 0, 0])
B_recall = recall(prediction=[0, 0, 0], labels=[0, 1, 0])
C_recall = recall(prediction=[0, 0, 1], labels=[0, 0, 1])

and RStd = Std( [ A_recall, B_recall, C_recall ] )?

Thanks!! :D

**Comment by chujiezheng** [comment]
No. The recall of A is P(prediction=A|gt=A)=1/1=1, while recall of B is
0/1=0 in your case.

**Comment by imhgchoi** [comment]
Got it! Thank you for your quick clarification :)
